version: "3.4"

networks:
    k6:
    grafana:

services:
    influxdb:
        image: influxdb:1.8
        #    entrypoint: /bin/sh
        #    user: root
        networks:
            - k6
            - grafana
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=k6

    grafana:
        image: grafana/grafana:8.5.21
        #    entrypoint: /bin/sh
        #    user: root
        networks:
            - grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
            - GF_SERVER_SERVE_FROM_SUB_PATH=${GF_SERVER_SERVE_FROM_SUB_PATH}
        volumes:
            - ./dashboards:/var/lib/grafana/dashboards
            - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
            - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

    k6:
        image: loadimpact/k6:latest
        #    entrypoint: /bin/sh
        #    user: root
        networks:
            - k6
        ports:
            - "6565:6565"
        environment:
            - K6_OUT=${K6_OUT}
            - DATASTORE_URL=${DATASTORE_URL}
            - CONNECTOR_GSHEET_SPREADSHEET_ID=${CONNECTOR_GSHEET_SPREADSHEET_ID}
            - CONNECTOR_GSHEET_PAGE_NAME=${CONNECTOR_GSHEET_PAGE_NAME}
            - CONNECTOR_GSHEET_START_COLUMN=${CONNECTOR_GSHEET_START_COLUMN}
            - CONNECTOR_GSHEET_END_COLUMN=${CONNECTOR_GSHEET_END_COLUMN}
            - CONNECTOR_GSHEET_START_ROW=${CONNECTOR_GSHEET_START_ROW}
            - CONNECTOR_GSHEET_END_ROW=${CONNECTOR_GSHEET_END_ROW}
            - CONNECTOR_CSV_FILE=${CONNECTOR_CSV_FILE}
            - CONNECTOR_POSTGRES_HOST=${CONNECTOR_POSTGRES_HOST}
            - CONNECTOR_POSTGRES_PORT=${CONNECTOR_POSTGRES_PORT}
            - CONNECTOR_POSTGRES_USERNAME=${CONNECTOR_POSTGRES_USERNAME}
            - CONNECTOR_POSTGRES_PASSWORD=${CONNECTOR_POSTGRES_PASSWORD}
            - CONNECTOR_POSTGRES_DB_NAME=${CONNECTOR_POSTGRES_DB_NAME}
            - CONNECTOR_POSTGRES_SCHEMA_NAME=${CONNECTOR_POSTGRES_SCHEMA_NAME}
            - CONNECTOR_POSTGRES_TABLE_NAME=${CONNECTOR_POSTGRES_TABLE_NAME}
        volumes:
            - .:/k6
        command: "k6 run /scripts/ewoks.js"
